### ISSUE TITLE
Provide ways to define Model directory

### ISSUE THREAD

**Issue by dedanirungu** [legodion/lucid#2]
I am developing my application using https://nwidart.com/laravel-modules and there is no way to auto-discover the models generated in the Modules folder.

Kindly provide way of specify preferred models files path,

**Comment by legodion** [comment]
Please check my comment in the PR you made. Let's continue discussion there.

**Comment by dedanirungu** [comment]
It might not work because the structure of files is as follows;
`[project_path]/Modules/[Module Name]/Entities/[Model Name].php`

Unless the config takes wildcard eg
`[project_path]/Modules/*/Entities/*.php`

for example, my system has the following structure.

Blogs

```
/var/www/html/laravel/Modules/Blog/Entities/Post.php
/var/www/html/laravel/Modules/Blog/Entities/Category.php
```
Media
`/var/www/html/laravel/Modules/Media/Entities/File.php`

School
`/var/www/html/laravel/Modules/School/Entities/Student.php`

**Comment by dedanirungu** [comment]
What is your take?

**Comment by legodion** [comment]
I don't want to tightly couple this package with your package.

We need to find an alternative way, like using config files.

**Comment by dedanirungu** [comment]
I have decided to create a fork of the project.

https://github.com/mybizna/lucid

We shall collaborate on future development. eg 
Foreign relationship and enum issues

**Comment by legodion** [comment]
ok cool
